name: Generate Pacman Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate SVG

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SVGs
        uses: yassinebridi/pacman-contribution-graph@main
        with:
          output_path: output/
          commit: true
