name: Generate Snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  # A cada 12 horas
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Verificar se snake.svg foi gerado
        run: |
          echo "Arquivos na pasta dist:"
          ls -la dist
          if [ ! -f dist/snake.svg ]; then
            echo "Erro: snake.svg não foi gerado"
            exit 1
          fi

      - name: Push snake.svg para o branch output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
